<a href="https://colab.research.google.com/github/arnabmy/tensorflow/blob/main/Tensorflow_sequential_model_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten,Dense

In [5]:
model = Sequential([
    Dense(64, activation='relu',input_shape=(784,)),
    Dense(10, activation='softmax')
])

In [7]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_5 (Dense)              (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


Alternate way

In [8]:
model = Sequential()
model.add( Dense(64, activation='relu',input_shape=(784,)))
model.add(Dense(10,activation='softmax'))

In [9]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_7 (Dense)              (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


Using Flatten

In [13]:
model = Sequential([
     Flatten(input_shape=(28,28)),
     Dense(64,activation='relu'),
     Dense(10,activation='softmax')               
])

In [14]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense_8 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_9 (Dense)              (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


In [26]:
# Build the sequential feedforward network
model = Sequential([
     Flatten(input_shape=(28,28)),
     Dense(16,activation='relu', name='layer1'),
     Dense(16,activation='relu',name='layer2'),
     Dense(10,activation='softmax')               
])

In [27]:
model.weights

[<tf.Variable 'layer1/kernel:0' shape=(784, 16) dtype=float32, numpy=
 array([[-0.00684697, -0.07381336, -0.00268139, ..., -0.05042892,
          0.00965709, -0.03419233],
        [ 0.03711868,  0.02374838, -0.01758649, ..., -0.01720928,
          0.05031537,  0.06001809],
        [ 0.03757225, -0.07829721,  0.08627766, ..., -0.07462711,
          0.03539503,  0.08046609],
        ...,
        [-0.01504648,  0.01529919,  0.02837999, ..., -0.07242312,
         -0.07592991, -0.06995101],
        [-0.03161647,  0.0633519 , -0.01181083, ..., -0.04812991,
         -0.034254  ,  0.00654458],
        [-0.03269254,  0.05560572,  0.02963842, ...,  0.04513505,
          0.07702719, -0.02005036]], dtype=float32)>,
 <tf.Variable 'layer1/bias:0' shape=(16,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=float32)>,
 <tf.Variable 'layer2/kernel:0' shape=(16, 16) dtype=float32, numpy=
 array([[-0.03781742,  0.13109228, -0.03894943,  0.201508

In [28]:
model.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_3 (Flatten)          (None, 784)               0         
_________________________________________________________________
layer1 (Dense)               (None, 16)                12560     
_________________________________________________________________
layer2 (Dense)               (None, 16)                272       
_________________________________________________________________
dense_19 (Dense)             (None, 10)                170       
Total params: 13,002
Trainable params: 13,002
Non-trainable params: 0
_________________________________________________________________


In [29]:
# Build the sequential feedforward network
model = Sequential([
     Flatten(input_shape=(64,)),
     Dense(16,activation='relu', name='layer1'),
     Dense(16,activation='relu',name='layer2'),
     Dense(16,activation='relu',name='layer3'),
     Dense(8,activation='softmax')               
])

In [30]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_4 (Flatten)          (None, 64)                0         
_________________________________________________________________
layer1 (Dense)               (None, 16)                1040      
_________________________________________________________________
layer2 (Dense)               (None, 16)                272       
_________________________________________________________________
layer3 (Dense)               (None, 16)                272       
_________________________________________________________________
dense_20 (Dense)             (None, 8)                 136       
Total params: 1,720
Trainable params: 1,720
Non-trainable params: 0
_________________________________________________________________
